name: Main workflow 

on: push

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies 
        run: npm install
      - name: Run jest tests
        run: npm run test
      - name: Run Cypress tests
        run: npm run cy:test
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v2.1.1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Install dependencies
        run: npm install
      - name: Setup Github credentials
        run: git config --global user.email "mps.bilo@gmail.com" && git config --global user.name "mpsb"
      - name: Deploy
        run: npm run deploy
