name: Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install other dependencies for jest
        run: npm install
      - name: Run jest tests
        run: npm run test
      - name: Run Cypress tests
        run: npm run cy:test
